### ISSUE TITLE
ACESS should be ACCESS, ADRESS should be ADDRESS

### ISSUE THREAD

**Issue by sompylasar** [fernandoneto/docker-sinopia#1]
`PRIVATE_PACKAGES_ACESS`
`PACKAGES_ACESS`
`LISTEN_ADRESS`

https://en.wiktionary.org/wiki/access
https://en.wiktionary.org/wiki/address

**Comment by fernandoneto** [comment]
@sompylasar 
just correct that. thanks

**Comment by sompylasar** [comment]
@fernandoneto please update the readme, too. thanks.
